const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.wrap,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sine: 0},
	{ombak1: 0},
	{ombak2: 0},
	{Rotate: 0},
	{matahari: 0},
	{awanhitam1: 0},
	{awan1: 0},
	{cloud1: 0},
	{awanPutih4: 0},
	{awan3: 0},
	{awan4: 0},
	{riak1: 0},
	{riak3: 0},
	{riak2: 0},
	{riak4: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{TiledBackground: 0},
	{Sprite3: 0},
	{Wrap: 0},
	{Sprite4: 0},
	{Particles: 0},
	{uap: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{opacityAwan: 0},
	{Pin: 0},
	{awan4Hitam: 0},
	{TiledBackground2: 0},
	{boxOpacity: 0},
	{global: 0},
	{Sprite5: 0},
	{Bullet: 0},
	{awan4Hitam2: 0},
	{batas: 0},
	{Particles2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{sirkulasi: 0},
	{sirkulasi2: 0},
	{sirkulasi3: 0},
	{sirkulasi4: 0},
	{TiledBackground3: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Solid: 0},
	{back: 0},
	{Sprite15: 0},
	{awanPutih2: 0},
	{kondensasi: 0},
	{Infiltrasi: 0},
	{Presipitasi: 0},
	{Adveksi: 0},
	{Evaporasi: 0},
	{batas2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ombak1: class extends self.ISpriteInstance {},
	ombak2: class extends self.ISpriteInstance {},
	matahari: class extends self.ISpriteInstance {},
	awanhitam1: class extends self.ISpriteInstance {},
	awan1: class extends self.ISpriteInstance {},
	cloud1: class extends self.ISpriteInstance {},
	awanPutih4: class extends self.ISpriteInstance {},
	awan3: class extends self.ISpriteInstance {},
	awan4: class extends self.ISpriteInstance {},
	riak1: class extends self.ISpriteInstance {},
	riak3: class extends self.ISpriteInstance {},
	riak2: class extends self.ISpriteInstance {},
	riak4: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	uap: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	awan4Hitam: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	boxOpacity: class extends self.ITiledBackgroundInstance {},
	global: class extends self.IArrayInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	awan4Hitam2: class extends self.ISpriteInstance {},
	batas: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	sirkulasi: class extends self.ISpriteInstance {},
	sirkulasi2: class extends self.ISpriteInstance {},
	sirkulasi3: class extends self.ISpriteInstance {},
	sirkulasi4: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	back: class extends self.ITiledBackgroundInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	awanPutih2: class extends self.ISpriteInstance {},
	kondensasi: class extends self.ISpriteInstance {},
	Infiltrasi: class extends self.ISpriteInstance {},
	Presipitasi: class extends self.ISpriteInstance {},
	Adveksi: class extends self.ISpriteInstance {},
	Evaporasi: class extends self.ISpriteInstance {},
	batas2: class extends self.ITiledBackgroundInstance {}
}